param(
    [switch]$NoStart,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$HERMES_DIR = "$env:USERPROFILE\.hermes"
$COMPOSE_FILE = Join-Path $PWD "docker-compose.hermes.yml"
$CONFIG_FILE = Join-Path $HERMES_DIR "config.yaml"
$ENV_FILE = Join-Path $HERMES_DIR ".env"

function Write-Step($s) { Write-Host "`n==> $s" -ForegroundColor Cyan }
function Write-Info($s)  { Write-Host "    $s" -ForegroundColor Gray }
function Write-Ok($s)    { Write-Host "  [v] $s" -ForegroundColor Green }
function Write-Warn($s)  { Write-Host "  [!] $s" -ForegroundColor Yellow }

Write-Step "Scanning Docker for local AI backends..."

$detected = @{ ollama = @(); vllm = @(); lmstudio = @(); sglang = @(); llamacpp = @() }
$raw = docker ps --format "{{.ID}}|{{.Image}}|{{.Names}}|{{.Ports}}" 2>$null
$containers = if ($raw) { $raw -split "`n" } else { @() }

if ($containers.Count -eq 0) {
    Write-Warn "No Docker containers running -- skipping AI detection."
} else {
    foreach ($line in $containers) {
        $parts = $line -split "\|"
        $id = $parts[0]; $image = $parts[1]; $name = $parts[2]; $ports = $parts[3]
        Write-Info "  container: $name ($image)"

        if ($image -match "ollama") {
            $hostPort = $null
            if ($ports -match "0\.0\.0\.0:(\d+)->11434") { $hostPort = $matches[1] }
            $o = @{ Name = $name; HostPort = $hostPort; Models = @() }
            $detected.ollama += $o
            Write-Ok "Ollama detected on port $hostPort (container: $name)"
            try {
                $m = docker exec $name ollama list 2>$null
                if ($m) {
                    $detected.ollama[-1].Models = ($m -split "`n") | ForEach-Object { ($_ -split "\s+")[0] } | Where-Object { $_ -match "\S" -and $_ -ne "NAME" }
                    Write-Ok "  Ollama models: $($detected.ollama[-1].Models -join ', ')"
                }
            } catch { Write-Warn "  Could not list Ollama models" }
        }

        if ($image -match "vllm") {
            $hostPort = $null
            if ($ports -match "0\.0\.0\.0:(\d+)->8000") { $hostPort = $matches[1] }
            $detected.vllm += @{ Name = $name; HostPort = $hostPort }
            Write-Ok "vLLM detected on port $hostPort (container: $name)"
        }
    }

    $testPorts = @{ 1234 = "lmstudio"; 8080 = "llamacpp"; 8000 = "vllm"; 30000 = "sglang" }
    foreach ($port in $testPorts.Keys) {
        $tcp = netstat -an 2>$null | Select-String "LISTENING" | Select-String ":$port "
        if ($tcp) {
            $detected.lmstudio += @{ Name = "host-process"; HostPort = "$port" }
            Write-Ok "$($testPorts[$port]) endpoint detected on host port $port"
        }
    }
}

Write-Step "Selecting primary local AI endpoint..."

$endpoint = $null
$modelName = $null

# pick first Ollama whose port is actually listening
$liveOllama = $detected.ollama | Where-Object {
    $_.HostPort -and ($null -ne (netstat -an 2>$null | Select-String "LISTENING" | Select-String ":$($_.HostPort) "))
} | Select-Object -First 1
if (-not $liveOllama) { $liveOllama = $detected.ollama | Where-Object { $_.HostPort } | Select-Object -First 1 }

if ($liveOllama) {
    $epPort = $liveOllama.HostPort
    $endpoint = "http://host.docker.internal:$epPort/v1"
    $picked = $liveOllama.Models | Where-Object { $_ -notmatch "nomic|all-minilm|bge|embed" } | Select-Object -First 1
    if (-not $picked) { $picked = $liveOllama.Models | Select-Object -First 1 }
    $modelName = $picked
    Write-Ok "Primary endpoint: $endpoint  (model: $modelName)"
} elseif ($detected.vllm.Count -gt 0 -and $detected.vllm[0].HostPort) {
    $endpoint = "http://host.docker.internal:$($detected.vllm[0].HostPort)/v1"
    Write-Ok "Primary endpoint: $endpoint  (vLLM)"
} elseif ($detected.lmstudio.Count -gt 0) {
    $endpoint = "http://host.docker.internal:1234/v1"
    Write-Ok "Primary endpoint: $endpoint  (LM Studio)"
} else {
    Write-Warn "No local AI backend detected. Hermes will start with default provider."
    Write-Warn "Configure later with: docker exec hermes hermes model"
}

Write-Step "Preparing Hermes Agent configuration..."
if (-not (Test-Path $HERMES_DIR)) {
    New-Item -ItemType Directory -Path $HERMES_DIR -Force | Out-Null
    Write-Ok "Created $HERMES_DIR"
}

if ($endpoint) {
    $modelComment = ""
    if ($detected.ollama.Count -gt 0 -and $detected.ollama[0].Models.Count -gt 0) {
        $modelComment = "# Available models: $($detected.ollama[0].Models -join ', ')"
    }
$configContent = @"
# Hermes Agent config -- generated by deploy-hermes.ps1
$modelComment
model:
  default: "$modelName"
  provider: "custom"
  base_url: "$endpoint"
  api_key: ""
terminal:
  backend: "docker"
  timeout: 180
  lifetime_seconds: 300
tools:
  enabled: true
  auto_approve: false
memory:
  enabled: true
skills:
  auto_create: true
  auto_improve: true
"@
} else {
$configContent = @"
# Hermes Agent config -- generated by deploy-hermes.ps1
# No local AI detected. Edit to add your provider.
model:
  default: "openai/gpt-4o-mini"
  provider: "openrouter"
  base_url: "https://openrouter.ai/api/v1"
terminal:
  backend: "docker"
  timeout: 180
  lifetime_seconds: 300
tools:
  enabled: true
memory:
  enabled: true
skills:
  auto_create: true
"@
}

Set-Content -Path $CONFIG_FILE -Value $configContent -Encoding Default
Write-Ok "Written $CONFIG_FILE"

if (-not (Test-Path $ENV_FILE)) {
$envContent = @"
# Hermes Agent .env -- generated by deploy-hermes.ps1
# Add API keys for tools you want to use:
# EXA_API_KEY=
# FIRECRAWL_API_KEY=
# FAL_KEY=
# BROWSERBASE_API_KEY=
# TELEGRAM_BOT_TOKEN=
# SLACK_BOT_TOKEN=
"@
    Set-Content -Path $ENV_FILE -Value $envContent -Encoding Default
    Write-Ok "Written $ENV_FILE"
} else {
    Write-Info "$ENV_FILE already exists, keeping as-is"
}

Write-Step "Generating Docker Compose file..."
$HERMES_DIR_FWD = $HERMES_DIR -replace '\\', '/'
$composeContent = @"
services:
  gateway:
    image: nousresearch/hermes-agent:latest
    container_name: hermes
    restart: unless-stopped
    volumes:
      - "${HERMES_DIR_FWD}:/opt/data"
    environment:
      - HERMES_UID=10000
      - HERMES_GID=10000
    ports:
      - "127.0.0.1:9118:9118"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["gateway", "run"]
  dashboard:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-dashboard
    restart: unless-stopped
    depends_on:
      - gateway
    volumes:
      - "${HERMES_DIR_FWD}:/opt/data"
    environment:
      - HERMES_UID=10000
      - HERMES_GID=10000
      - HERMES_DASHBOARD_HOST=0.0.0.0
    ports:
      - "127.0.0.1:9119:9119"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["dashboard", "--host", "0.0.0.0", "--port", "9119", "--no-open", "--insecure"]
"@

Set-Content -Path $COMPOSE_FILE -Value $composeContent -Encoding Default
Write-Ok "Written $COMPOSE_FILE"

if (-not $NoStart) {
    Write-Step "Starting Hermes Agent via Docker Compose..."
    Write-Info "Running: docker compose -f $COMPOSE_FILE up -d"
    docker compose -f $COMPOSE_FILE up -d
    if ($LASTEXITCODE -eq 0) {
        Write-Ok "Hermes Agent is starting!"
        Start-Sleep -Seconds 3
        docker ps --filter "name=hermes" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
        Write-Host ""
        Write-Host "  Hermes Agent deployed!" -ForegroundColor Green
        Write-Host "  Chat: docker exec -it hermes hermes" -ForegroundColor Gray
        Write-Host "  Dashboard: http://localhost:9119" -ForegroundColor Gray
        if ($endpoint) {
            Write-Host "  Local AI: $endpoint  (model: $modelName)" -ForegroundColor Yellow
        }
        Write-Host "  Stop: docker compose -f $COMPOSE_FILE down" -ForegroundColor Gray
    } else {
        Write-Warn "Docker Compose failed. Check logs: docker compose -f $COMPOSE_FILE logs"
    }
} else {
    Write-Ok "Config generated. To start:"
    Write-Host "    docker compose -f $COMPOSE_FILE up -d" -ForegroundColor Yellow
    Write-Host "    docker exec -it hermes hermes" -ForegroundColor Yellow
}
